//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTBookApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Orders = new HashSet<Order>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the Username")]
        [Display(Name = "Username")]
        public string AccID { get; set; }
        [Required(ErrorMessage = "Please enter the Password")]
        [Display(Name = "Password")]
        public string pass { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter the Full name")]
        [Display(Name = "Full Name")]
        public string fullname { get; set; }
        [Required(ErrorMessage = "Please enter the Email")]
        public string email { get; set; }
        [Required(ErrorMessage = "Please enter the Tel")]
        public string tel { get; set; }
        public Nullable<int> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
