//------------------------------------------------------------------------------
// <auto-generated>
namespace FPTBookApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Nullable<int> OrderID { get; set; }
        public System.DateTime Orderdate { get; set; }
        public int ID { get; set; }
        public string AccID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
