//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTBookApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public string ProID { get; set; }
        public int price { get; set; }
        public int qty { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual product product { get; set; }
        public virtual Order Order { get; set; }
    }
}
